/* ========================================
 *
 * Copyright YOUR COMPANY, THE YEAR
 * All Rights Reserved
 * UNPUBLISHED, LICENSED SOFTWARE.
 *
 * CONFIDENTIAL AND PROPRIETARY INFORMATION
 * WHICH IS THE PROPERTY OF your company.
 *
 * ========================================
*/
#ifndef _INTERRUPT_ROUTINES_H_
    // Header guard
    #define _INTERRUPT_ROUTINES_H_

    #include "project.h"

    /**
    *   \brief ISR code generated by FIFO overflow
    */
    CY_ISR_PROTO(Custom_FIFO_ISR);
    
    /**
    *   \brief ISR code generated by TIMER overflow
    */
    CY_ISR_PROTO(custom_TIMER_ISR);

    #define FIFO_DATA_DIM 192 // 6 output registers of 32 levels
    
    #define SENSOR_DATA_DIM 32 //the fifo stores 32 values of acceleration so we need 23 values of the sensor (potentiometer/photoresistor)

    _VOLATILE uint8_t AccData[FIFO_DATA_DIM];

    _VOLATILE uint8_t FlagFifo;

    _VOLATILE uint8_t CountSensor;
    
    _VOLATILE uint16_t SensData[SENSOR_DATA_DIM];
    
    _VOLATILE uint8_t SensBytes[2*SENSOR_DATA_DIM];
    
    _VOLATILE uint8_t SensBytes_old[2*SENSOR_DATA_DIM];
    
    _VOLATILE uint8_t SensorDataReady; 
    
    




#endif
/* [] END OF FILE */
