/* ========================================
 *
 * Copyright YOUR COMPANY, THE YEAR
 * All Rights Reserved
 * UNPUBLISHED, LICENSED SOFTWARE.
 *
 * CONFIDENTIAL AND PROPRIETARY INFORMATION
 * WHICH IS THE PROPERTY OF your company.
 *
 * ========================================
*/
#ifndef _INTERRUPT_ROUTINES_H_
    // Header guard
    #define _INTERRUPT_ROUTINES_H_

    #include "project.h"

    /**
    *   \brief ISR code generated by FIFO overflow
    */
    CY_ISR_PROTO(Custom_FIFO_ISR);

    #define FIFO_DATA_DIM 192 // 6 output registers of 32 levels

    _VOLATILE uint8_t AccData[FIFO_DATA_DIM];



#endif
/* [] END OF FILE */
